// apps/vite-react/src/App.tsx
import { AvatarButton, SideNavigation, NavigationItem } from '@discord-clone/react'

const App = () => {
	return (
		<section className="flex w-screen h-screen bg-pink-700 overflow-clip">
			<SideNavigation></SideNavigation>
			<section
				id="subnavigation"
				className="w-[15.5rem] h-full bg-gray-900 flex-shrink-0"
			></section>
			<main id="main" className="flex-1 h-full bg-slate-800"></main>
		</section>
	)
}

export { App }

// apps/vite-vue/src/App.vue
<script setup lang="ts">
</script>

<template>
  <div class="flex w-screen h-screen bg-pink-700 overflow-clip">
    <section id="sidebar" class="flex-shrink-0 w-16 h-full bg-zinc-800"></section>
    <section id="subnavigation" class="w-[15.5rem] h-full bg-gray-900 flex-shrink-0"></section>
    <main id="main" class="flex-1 h-full bg-slate-800"></main>
  </div>
</template>
